CREATE OR REPLACE PROCEDURE add_emp(p_ID NUMBER, p_NAME VARCHAR2, p_salary NUMBER)
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
   INSERT INTO emp1 VALUES (p_id, p_name, p_salary);
   print(SQL%ROWCOUNT||' row inserted');
   COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/
